### ISSUE TITLE
Explore database works with oracle db

### ISSUE THREAD

**Issue by simonvadee** [arkhn/pagai#26]

**Comment by achauve** [comment]
Étapes envisagées : 

- ajouter des tests sans changer le code actuel (validation sur une base postgres)
- remplacer les requêtes low level par des appels plus haut-niveau à Sqlalchemy (ce qui permettra de factoriser les requêtes à Postgres, Oracle et plus tard d'autres comme MySQL ou MS SQL Server)
- ajouter une base oracle pour les tests et faire les corrections nécessaires
