### ISSUE TITLE
Add MSSQL support

### ISSUE THREAD

**Issue by nriss** [arkhn/pagai#44]
To complete pagai DB supports, add Microsoft SQL server.

We can use PyODBC to connect to the MSSQL server : 
https://docs.sqlalchemy.org/en/13/dialects/mssql.html#module-sqlalchemy.dialects.mssql.pyodbc

To connect to the MSSQL server, this method worked in local :
`engine = sqlalchemy.create_engine("mssql+pyodbc://user:pasword@IP:port/dbName?driver=driver_name")`
The driver_name can be found there : `cat /etc/odbcinst.ini` (replace spaces by +)

You can verify that the connection worked with : `engine.table_names()`

**Comment by nriss** [comment]
To connect to the MSSQL server, this method worked :
engine = sqlalchemy.create_engine("mssql+pyodbc://user:pasword@IP:^ort/dbName?driver=ODBC+Driver+17+for+SQL+Server")
The driver name can be found there : `cat /etc/odbcinst.ini`

**Comment by elsiehoffet-94** [comment]
An example of driver name is "ODBC+Driver+17+for+SQL+Server".
The docker base for pagai will probably require a different odbc driver than for oracle and postgre.
