### ISSUE TITLE
object of type time is not JSON serializable

### ISSUE THREAD

**Issue by simonvadee** [arkhn/pagai#55]
example: staging
Croix rouge --> table RESIDANT_PLAN_ANI

**Comment by Jasopaum** [comment]
I can't replicate the issue on staging, is the resource gone?

**Comment by elsiehoffet-94** [comment]
@nriss do you know something about this issue ?

**Comment by nriss** [comment]
When we try to make the preview of the first lines of RESIDANT_PLAN_ANI table on staging, we get this error:

`Object of type time is not JSON serializable `

**Comment by nriss** [comment]
I think it is the date format of mssql which cause problem with sqlalchemy (maybe DateInscription or HeureInscription column)
