### ISSUE TITLE
Table preview request on pyrog return empty arrays

### ISSUE THREAD

**Issue by nriss** [arkhn/pagai#56]
The bug is temporarily resolved after updating the credentials

## Environment
MSSQL db & PostgreSQL, on staging

**Comment by nriss** [comment]
table preview returns : {"fields":[],"rows":[[],[],[],[],[],[],[]]}
![image](https://user-images.githubusercontent.com/48218773/93498021-83d8b880-f911-11ea-841f-998982d3994a.png)

**Comment by nriss** [comment]
This issue seems to be on MSSQL db only. Maybe because the MSSQL docker image is down regularly ?

**Comment by simonvadee** [comment]
To resolve this issue, investigate the DB connection which may time out when called multiple times (connection not refreshed ?)

**Comment by nriss** [comment]
Adding High priority label because reader users cannot see the table, cannot update the table schema, cannot make any previews
