### ISSUE TITLE
Error while trying to make a FHIR preview of staging > EtablissementFictif > CarePlan

### ISSUE THREAD

**Issue by nriss** [arkhn/pagai#57]
`<html> <head><title>502 Bad Gateway</title></head> <body> <center><h1>502 Bad Gateway</h1></center> <hr><center>nginx/1.17.3</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->`

**Comment by nriss** [comment]
Corrected after restarting reverse-proxy

**Comment by nriss** [comment]
Bug appeared again after restarting mssql docker image

**Comment by simonvadee** [comment]
does not occur anymore, don't know if it's skills or luck
